{% set name = "langchain-fireworks" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_fireworks-{{ version }}.tar.gz
  sha256: cc8c812c0a1199bdeaabc9210c713e9186784d83fe3c6bc4d98516959f200e8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=1.0.0,<2.0.0
    - fireworks-ai >=0.13.0,<1.0.0
    - openai >=2.0.0,<3.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0

test:
  imports:
    - langchain_fireworks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Fireworks and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
