{% set name = "langchain-fireworks" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_fireworks-{{ version }}.tar.gz
  sha256: cc6a04d5d5735bdea642de524cb4bca544b8ed8ca867a1d64ec47ea14367210a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=0.3.33,<0.4.0
    - fireworks-ai >=0.13.0
    - openai >=1.10.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0

test:
  imports:
    - langchain_fireworks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Fireworks and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
