{% set name = "langchain-fireworks" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_fireworks-{{ version }}.tar.gz
  sha256: 1ff168cf40b80f78b955a5f7d2e2e2b400510fab3dfc0a193fa2296f871e836a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core <1.0.0,>=0.3.47
    - fireworks-ai >=0.13.0
    - openai <2.0.0,>=1.10.0
    - requests <3,>=2
    - aiohttp <4.0.0,>=3.9.1

test:
  imports:
    - langchain_fireworks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Fireworks and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
